repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: "mkdocs.yml"
    -   id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: "examples"
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json

    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: []
        files: .

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell # See setup.cfg for args

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: []

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: []
        files: .

-   repo: https://github.com/asottile/pyupgrade  # update python syntax
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/pdm-project/pdm
    rev: 2.4.3
    hooks:
        -   id: pdm-lock-check
        -   id: pdm-export
            name: pdm export prod
            args: ['--prod', '-o', 'requirements.txt', '--without-hashes']
            files: ^pdm.lock$
        -   id: pdm-export
            name: pdm export dev
            args: ['-d', '-o', 'requirements-dev.txt', '--without-hashes']
            files: ^pdm.lock$

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
        -   id: mypy
            args: [src]
            pass_filenames: false
            additional_dependencies:
              - pystac
              - pytest-vcr
              - types-requests

-   repo: local
    hooks:
        -   id: clean
            name: clean
            entry: pdm
            args: ["run", "clean"]
            language: system
            pass_filenames: false
