repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: "mkdocs.yml"
    -   id: check-added-large-files
        args: ['--maxkb=3000']
        exclude: "examples"
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: []
        files: .

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell # See setup.cfg for args
        args: [--skip=*.yaml]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: []

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: []
        files: .

-   repo: https://github.com/asottile/pyupgrade  # update python syntax
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
        -   id: mypy
            args: [src]
            pass_filenames: false
            additional_dependencies:
              - pystac
              - pytest-vcr
              - types-requests
              - types-aiofiles

-   repo: local
    hooks:
        -   id: pdm-lock-check
            name: pdm-lock-check
            entry: pdm
            args: ["lock", "--check"]
            language: python
            pass_filenames: false
        -   id: pdm-export
            name: pdm-export-dev
            entry: pdm
            args: ['export', '-d', '-o', 'requirements-dev.txt', '--without-hashes']
            language: python
            pass_filenames: false
        -   id: pdm-export
            name: pdm-export-prod
            entry: pdm
            args: ['export', '--prod', '-o', 'requirements.txt', '--without-hashes']
            language: python
            pass_filenames: false
        -   id: clean
            name: clean
            entry: pdm
            args: ["run", "clean"]
            language: system
            pass_filenames: false
