name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - x64
        pdm-version:
          - 2.4.5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
          version: ${{ matrix.pdm-version }}
      -  name: Install dependencies
         run: |
          pdm sync -d -G test
      -  name: Run pre-commit
         run: |
          pdm run pre-commit run --all-files
      - name: Run pytest
        run: |
          pdm run pytest --cov=pystac_user --cov-config=setup.cfg --cov-report=xml tests
      - name: Upload All coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  analyze:
    name: Analyze
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - python
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
