name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "*.md"
      - docs/**
      - .github/workflows/doc.yml
      - "pystac_user/**"

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.9
          architecture: "x64"
      - name: Get dosc requirements
        run: |
          pdm export -G doc -o requirements-doc.txt --without-hashes
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
          architecture: "x64"
      - name: Install dependencies
        run: |
          pip install -r requirements-doc.txt
      - name:  Get Changelog
        run: |
          cp CHANGELOG.md docs/changelog.md
      - name: Build Documentation
        run: |
          mkdocs gh-deploy --force
